CREATE TABLE IF NOT EXISTS Civil (
    id serial NOT NULL,
    Nombres VARCHAR(150) NOT NULL,
    Apellidos VARCHAR(150) NOT NULL,
    DocuIde int(150) NOT NULL UNIQUE,
    Direccion varchar(256) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    Nacionalidad VARCHAR(256) NOT NULL,
    EstadoCivil VARCHAR(150) NOT NULL,
    Genero VARCHAR(150) NOT NULL,
    FechaNacimiento datetime NOT NULL,
    LugarNacimiento VARCHAR(150) NOT NULL,
    FechaFallecimiento datetime NOT NULL,
    LugarFallecimiento VARCHAR(150) NOT NULL,
    CausasFallecimiento VARCHAR(150) NOT NULL,
    Profesion VARCHAR(150) NOT NULL,
    NroPasaporte int(150) NOT NULL UNIQUE,
    NombresApellidosPadre VARCHAR(150) NOT NULL,
    DocuIdePadre int(150) NOT NULL UNIQUE,
    ProfesionPadre VARCHAR(150) NOT NULL,
    ResidenciaPadre VARCHAR(150) NOT NULL,
    NombresApellidosMadre VARCHAR(150) NOT NULL,
    DocuIdeMadre int(150) NOT NULL UNIQUE,
    ProfesionMadre VARCHAR(150) NOT NULL,
    ResidenciaMadre VARCHAR(150) NOT NULL,
    NombresApellidoshijo1 VARCHAR(150) NOT NULL,
    DocuIdehijo1 int(150) NOT NULL UNIQUE,
    EdadHijo1 int(150) NOT NULL,
    ActaNaciNro1 int(150) NOT NULL UNIQUE,
    FechaNaci1 datetime NOT NULL,
    NombresApellidoshijo2 VARCHAR(150) NOT NULL,
    DocuIdehijo2 int(150) NOT NULL UNIQUE,
    EdadHijo2 int(150) NOT NULL,
    ActaNaciNro2 int(150) NOT NULL UNIQUE,
    FechaNaci2 datetime NOT NULL,
    NombresApellidoshijo3 VARCHAR(150) NOT NULL,
    DocuIdehijo3 int(150) NOT NULL UNIQUE,
    EdadHijo3 int(150) NOT NULL,
    ActaNaciNro3 int(150) NOT NULL UNIQUE,
    FechaNaci3 datetime NOT NULL,
    NombresApellidoshijo4 VARCHAR(150) NOT NULL,
    DocuIdehijo4 int(150) NOT NULL UNIQUE,
    EdadHijo4 int(150) NOT NULL,
    ActaNaciNro4 int(150) NOT NULL UNIQUE,
    FechaNaci4 datetime NOT NULL,
    Comunidad VARCHAR(150) NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Documento (
    id serial NOT NULL,
    Codigo int NOT NULL UNIQUE,
    Fecha datetime NOT NULL,
    Tipo text NOT NULL,
    Descripcion text NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp NOT NULL,
    CONSTRAINT pk_notes PRIMARY KEY(id),
    CONSTRAINT fk_posts_users FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS Registrador (
    id serial NOT NULL,
    Nombres VARCHAR(150) NOT NULL,
    Apellidos VARCHAR(150) NOT NULL,
    DocuIde int(150) NOT NULL UNIQUE,
    Oficina VARCHAR(256) NOT NULL,
    Resolucion VARCHAR(150) NOT NULL,
    Fecha datetime NOT NULL,
    Resolucion VARCHAR(150) NOT NULL,
    Fecha datetime NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp NOT NULL,
    CONSTRAINT pk_notes PRIMARY KEY(id),
    CONSTRAINT fk_posts_users FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS Solicitud (
    id serial NOT NULL,
    Numero int(150) NOT NULL UNIQUE,
    NumeroActa int(150) NOT NULL UNIQUE,
    Fecha datetime NOT NULL,
    FechaActa datetime NOT NULL,
    NacionalidadCivil VARCHAR(150) NOT NULL,
    DocuIdeCivil int(150) NOT NULL UNIQUE,
    DocuIdeRegistrador int(150) NOT NULL UNIQUE,
    CodigoDocumento int(150) NOT NULL UNIQUE,
    EstadoDocumento text NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp NOT NULL,
    CONSTRAINT pk_notes PRIMARY KEY(id),
    CONSTRAINT fk_posts_users FOREIGN KEY(user_id) REFERENCES users(id)
);